#!/usr/bin/env python3
"""
Quantum Random Number Generator - ANU QRNG API client.

Fetches truly random numbers generated by quantum vacuum fluctuations.
Can save the raw data as a binary file.

Usage examples:
    python quantum_random.py -l 20
    python quantum_random.py --length 5 --type uint16
    python quantum_random.py -l 8 -t hex8 -s 3
    python quantum_random.py -l 10 -t uint16 -o random.bin
"""

import os
import sys
import argparse
import struct
import requests
import json

# Read environment variables (with fallback for the URL)
API_KEY = os.environ.get("ANU_API_KEY")
API_URL = os.environ.get("ANU_API_URL", "https://api.quantumnumbers.anu.edu.au")

def get_random_numbers(length=10, data_type="uint8", block_size=None):
    """
    Fetch quantum random numbers from the ANU QRNG API.

    Parameters:
        length (int): Number of random values to request (1-1024)
        data_type (str): Type of data - 'uint8', 'uint16', 'hex8', or 'hex16'
        block_size (int, optional): Block size for hex types (1-10)

    Returns:
        list: List of random numbers (integers or hex strings)

    Raises:
        Exception: If the API key is missing, network errors occur,
                   or the response is malformed.
    """
    if not API_KEY:
        raise Exception(
            "Environment variable ANU_API_KEY is not set. "
            "Please set it before running (e.g., export ANU_API_KEY='your_key')."
        )

    # Validate parameters
    if not (1 <= length <= 1024):
        raise ValueError("length must be between 1 and 1024")
    if data_type not in ("uint8", "uint16", "hex8", "hex16"):
        raise ValueError("data_type must be 'uint8', 'uint16', 'hex8', or 'hex16'")
    if block_size is not None and not (1 <= block_size <= 10):
        raise ValueError("block_size must be between 1 and 10")

    params = {"length": length, "type": data_type}
    if block_size is not None:
        params["size"] = block_size

    headers = {"x-api-key": API_KEY}

    try:
        response = requests.get(API_URL, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()

        # The API returns either a direct array or an object with a "data" field
        if isinstance(data, list):
            return data
        if isinstance(data, dict) and "data" in data:
            return data["data"]
        raise Exception(f"Unexpected response format: {data}")

    except requests.exceptions.RequestException as e:
        raise Exception(f"API request failed: {e}")
    except json.JSONDecodeError as e:
        raise Exception(f"Failed to parse JSON response: {e}")

def convert_to_bytes(data, data_type):
    """
    Convert the list of random values into a bytes object suitable for binary output.

    Parameters:
        data (list): List of values (integers or hex strings)
        data_type (str): The data type used

    Returns:
        bytes: Raw binary data (big-endian for multi-byte values)

    Raises:
        ValueError: If conversion fails.
    """
    if data_type == "uint8":
        # Each value is 0–255, directly pack as bytes
        return bytes(data)

    elif data_type == "uint16":
        # Each value is 0–65535, pack as 2 bytes (big-endian)
        return b''.join(struct.pack('>H', v) for v in data)

    elif data_type == "hex8":
        # Each hex string represents one byte (e.g., "a3")
        return bytes(int(v, 16) for v in data)

    elif data_type == "hex16":
        # Each hex string represents two bytes (e.g., "1a2b")
        return b''.join(struct.pack('>H', int(v, 16)) for v in data)

    else:
        raise ValueError(f"Unsupported data type for binary output: {data_type}")

def main():
    parser = argparse.ArgumentParser(
        description="Fetch quantum random numbers from the ANU QRNG API."
    )
    parser.add_argument(
        "-l", "--length",
        type=int,
        default=10,
        help="Number of random values to request (1-1024, default: 10)"
    )
    parser.add_argument(
        "-t", "--type",
        choices=["uint8", "uint16", "hex8", "hex16"],
        default="uint8",
        help="Data type: uint8, uint16, hex8, or hex16 (default: uint8)"
    )
    parser.add_argument(
        "-s", "--block-size",
        type=int,
        default=None,
        help="Block size for hex types (1-10); only valid for hex8/hex16"
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default=None,
        help="Write raw binary data to this file (e.g., random.bin)"
    )

    args = parser.parse_args()

    # Additional validation
    if args.block_size is not None and args.type not in ("hex8", "hex16"):
        parser.error("--block-size can only be used with hex8 or hex16 data types.")

    try:
        numbers = get_random_numbers(
            length=args.length,
            data_type=args.type,
            block_size=args.block_size
        )
        print(f"Retrieved {len(numbers)} random numbers (type: {args.type}).")

        # If output file is specified, save as binary
        if args.output:
            raw_bytes = convert_to_bytes(numbers, args.type)
            with open(args.output, "wb") as f:
                f.write(raw_bytes)
            print(f"Binary data written to: {args.output} ({len(raw_bytes)} bytes)")

        # Always print the numbers in a readable form (hex for hex types, decimal for ints)
        #if args.type in ("hex8", "hex16"):
            #print("Values (hex):", numbers)
        #else:
            #print("Values:", numbers)

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
